services:
  pyspark-notebook:
    image: quay.io/jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
